name: flutter_sample
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  image_picker: ^1.0.5
  image_picker_android: ^0.8.9+1
  path: ^1.8.3
  pigeon: ^15.0.2
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
